#!/usr/bin/env node
/**
 * Prepares the removal of beneficiaries, with all their declarations, from the Historical
 * Declarations archive, for example individual practitioners.
 *
 *   node scripts/archive-removal.mjs <reviewed.csv | ids.txt> [--out <dir>]
 *
 * Input: the reviewed candidate list saved as CSV (comma- or semicolon-separated); every row
 * whose "Individual?" column says yes is removed. Or a text file with one beneficiary ID per
 * line (# starts a comment).
 *
 * Output, in d1/historical-declarations/private/ unless --out says otherwise. That folder is
 * ignored by Git: these files identify people and must not be committed.
 *   remove-beneficiaries.sql    DELETE statements for the remote D1 database
 *   excluded-beneficiaries.txt  the IDs, for scripts/build-final-historical-declarations.py
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const CHUNK = 100;

// RFC 4180 CSV with the delimiter taken from the header line: Excel saves CSV with
// semicolons in locales such as Belgium and Germany.
export function parseCsv(text) {
  const input = String(text).replace(/^﻿/, '');
  const header = input.slice(0, input.search(/\r?\n|$/)).replace(/"[^"]*"/g, '');
  const delimiter = (header.match(/;/g) || []).length > (header.match(/,/g) || []).length ? ';' : ',';
  const rows = [];
  let row = [];
  let field = '';
  let inQuotes = false;
  for (let i = 0; i < input.length; i += 1) {
    const char = input[i];
    if (inQuotes) {
      if (char === '"' && input[i + 1] === '"') { field += '"'; i += 1; }
      else if (char === '"') inQuotes = false;
      else field += char;
    } else if (char === '"') inQuotes = true;
    else if (char === delimiter) { row.push(field); field = ''; }
    else if (char === '\n' || char === '\r') {
      if (char === '\r' && input[i + 1] === '\n') i += 1;
      row.push(field); rows.push(row); row = []; field = '';
    } else field += char;
  }
  if (inQuotes) throw new Error('The CSV file has an unterminated quoted field.');
  if (field || row.length) { row.push(field); rows.push(row); }
  return rows.filter((cells) => cells.some((cell) => cell.trim()));
}

function checkId(id, where) {
  if (!UUID.test(id)) throw new Error(`${where}: "${id}" is not a beneficiary ID.`);
  return id.toLowerCase();
}

// The beneficiary IDs to remove, sorted and without duplicates.
export function readBeneficiaryIds(text, kind) {
  const ids = new Set();
  if (kind === 'csv') {
    const [header = [], ...records] = parseCsv(text);
    const decision = header.findIndex((name) => /^\s*(is_)?individual\b/i.test(name));
    const idColumn = header.findIndex((name) => /beneficiary[ _]id/i.test(name));
    if (decision < 0 || idColumn < 0) {
      throw new Error('The CSV file needs an "Individual?" column and a "Beneficiary ID" column.');
    }
    records.forEach((cells, index) => {
      if (/^\s*(yes|y)\s*$/i.test(cells[decision] || '')) {
        ids.add(checkId((cells[idColumn] || '').trim(), `CSV row ${index + 2}`));
      }
    });
  } else {
    String(text).split(/\r?\n/).forEach((line, index) => {
      const id = line.replace(/#.*/, '').trim();
      if (id) ids.add(checkId(id, `Line ${index + 1}`));
    });
  }
  return [...ids].sort();
}

export function buildRemovalSql(ids) {
  const lines = [
    `-- Removes ${ids.length} beneficiaries and all their declarations from the Historical Declarations archive.`,
    '-- Generated by scripts/archive-removal.mjs. Do not commit this file to Git.',
    '-- Run: npx wrangler d1 execute historical-declarations-final --remote --file=<this file>',
    '',
  ];
  for (let start = 0; start < ids.length; start += CHUNK) {
    const list = ids.slice(start, start + CHUNK).map((id) => `'${id}'`).join(', ');
    lines.push(`DELETE FROM declarations WHERE beneficiary_id IN (${list});`);
    lines.push(`DELETE FROM beneficiaries WHERE id IN (${list});`);
  }
  return `${lines.join('\n')}\n`;
}

function main(argv) {
  const outIndex = argv.indexOf('--out');
  const repoRoot = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
  const outDir = outIndex >= 0 ? argv[outIndex + 1] : path.join(repoRoot, 'd1', 'historical-declarations', 'private');
  const input = argv.find((arg, index) => !arg.startsWith('--') && !(outIndex >= 0 && index === outIndex + 1));
  if (!input || !outDir) {
    console.error('Usage: node scripts/archive-removal.mjs <reviewed.csv | ids.txt> [--out <dir>]');
    return 1;
  }
  const kind = input.toLowerCase().endsWith('.csv') ? 'csv' : 'txt';
  const ids = readBeneficiaryIds(readFileSync(input, 'utf8'), kind);
  if (ids.length === 0) {
    console.error('No beneficiaries to remove: no row says yes in the "Individual?" column.');
    return 1;
  }
  mkdirSync(outDir, { recursive: true });
  const sqlPath = path.join(outDir, 'remove-beneficiaries.sql');
  const idsPath = path.join(outDir, 'excluded-beneficiaries.txt');
  writeFileSync(sqlPath, buildRemovalSql(ids));
  writeFileSync(idsPath, `# Beneficiaries removed from the Historical Declarations archive. Do not commit.\n${ids.join('\n')}\n`);
  console.log(`${ids.length} beneficiaries to remove.`);
  console.log(`  ${sqlPath}`);
  console.log(`  ${idsPath}`);
  console.log('\nNext:');
  console.log(`  npx wrangler d1 execute historical-declarations-final --remote --file="${sqlPath}"`);
  console.log('  Keep excluded-beneficiaries.txt with the archive dump: every rebuild needs it');
  console.log('  (scripts/build-final-historical-declarations.py --exclude-beneficiaries).');
  return 0;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  try {
    process.exitCode = main(process.argv.slice(2));
  } catch (error) {
    console.error(error.message);
    process.exitCode = 1;
  }
}
